oeb check changes
Added analog wrapper support.
Clarified return codes.
Added analog/digital mix check.
Fixed run_cvc file name bug

diff --git a/check_user_oeb b/check_user_oeb
--- a/check_user_oeb
+++ b/check_user_oeb
@@ -2,6 +2,16 @@
 
 # check that the oeb pin is low/high based on io_in and io_out connections
 
+# Parameters are read from $WORK_ROOT/cvcrc.oeb which is copied from the default in $LVS_ROOT if non-existent.
+
+# Return codes
+# 1: LVS_ROOT not set
+# 2: Missing file
+# 3: Unrecognized block name
+# 4: CVC execution error
+# 5: OEB related error
+# 6: OEB related warning
+
 export DESIGN_NAME=$1
 
 # Check for LVS_ROOT
@@ -18,6 +28,8 @@ export LOG_ROOT SIGNOFF_ROOT WORK_ROOT
 mkdir -p $LOG_ROOT $SIGNOFF_ROOT $WORK_ROOT
 export RESULTS_DIR=$WORK_ROOT/ext
 
+rm -f $WORK_ROOT/cvc.oeb* $LOG_ROOT/cvc.oeb* $SIGNOFF_ROOT/cvc.oeb*
+
 if [[ ! -f $WORK_ROOT/cvcrc.oeb ]]; then
 	if [[ ! -f $WORK_ROOT/cvcrc ]]; then
 		cp $LVS_ROOT/tech/$PDK/cvcrc $WORK_ROOT/cvcrc
@@ -25,7 +37,32 @@ if [[ ! -f $WORK_ROOT/cvcrc.oeb ]]; then
 	sed 's/cvc.log/cvc.oeb.log/' $WORK_ROOT/cvcrc >$WORK_ROOT/cvcrc.oeb
 fi
 
-if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
+# Create cdl file from extracted spice file if it doesn't exist
+if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.cdl.gz || $RESULTS_DIR/$DESIGN_NAME.gds.spice -nt $RESULTS_DIR/$DESIGN_NAME.cdl.gz ]]; then
+	if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.gds.spice ]]; then
+		echo "Could not create cdl file from $RESULTS_DIR/$DESIGN_NAME.gds.spice"
+		exit 2
+	else
+		echo "Creating $RESULTS_DIR/$DESIGN_NAME.cdl"
+		$LVS_ROOT/spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice |
+			gzip -c >$RESULTS_DIR/$DESIGN_NAME.cdl.gz
+	fi
+fi
+
+# Copy default power file to work area if it doesn't exist
+shopt -u nocasematch
+BASE_NAME=${DESIGN_NAME//[A-Z0-9][A-Z0-9]_}  # remove leading 2 byte prefices
+if [[ ! -f $WORK_ROOT/cvc.power.$DESIGN_NAME ]]; then
+	if [[ -f $LVS_ROOT/tech/$PDK/cvc.power.$BASE_NAME ]]; then
+		cp $LVS_ROOT/tech/$PDK/cvc.power.$BASE_NAME $WORK_ROOT/cvc.power.$DESIGN_NAME
+	else
+		echo "
+ERROR: Could not find $WORK_ROOT/cvc.power.$DESIGN_NAME"
+		exit 2
+	fi
+fi
+
+if [[ $DESIGN_NAME == *user_analog_project_wrapper ]]; then
 	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
 		gn io_in[0]
 		gn io_in[1]
@@ -54,17 +91,6 @@ if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
 		gn io_in[24]
 		gn io_in[25]
 		gn io_in[26]
-		gn io_in[27]
-		gn io_in[28]
-		gn io_in[29]
-		gn io_in[30]
-		gn io_in[31]
-		gn io_in[32]
-		gn io_in[33]
-		gn io_in[34]
-		gn io_in[35]
-		gn io_in[36]
-		gn io_in[37]
 		gn io_in_3v3[0]
 		gn io_in_3v3[1]
 		gn io_in_3v3[2]
@@ -92,17 +118,6 @@ if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
 		gn io_in_3v3[24]
 		gn io_in_3v3[25]
 		gn io_in_3v3[26]
-		gn io_in_3v3[27]
-		gn io_in_3v3[28]
-		gn io_in_3v3[29]
-		gn io_in_3v3[30]
-		gn io_in_3v3[31]
-		gn io_in_3v3[32]
-		gn io_in_3v3[33]
-		gn io_in_3v3[34]
-		gn io_in_3v3[35]
-		gn io_in_3v3[36]
-		gn io_in_3v3[37]
 		gn io_out[0]
 		gn io_out[1]
 		gn io_out[2]
@@ -130,17 +145,6 @@ if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
 		gn io_out[24]
 		gn io_out[25]
 		gn io_out[26]
-		gn io_out[27]
-		gn io_out[28]
-		gn io_out[29]
-		gn io_out[30]
-		gn io_out[31]
-		gn io_out[32]
-		gn io_out[33]
-		gn io_out[34]
-		gn io_out[35]
-		gn io_out[36]
-		gn io_out[37]
 		gn io_oeb[0]
 		gn io_oeb[1]
 		gn io_oeb[2]
@@ -168,20 +172,45 @@ if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
 		gn io_oeb[24]
 		gn io_oeb[25]
 		gn io_oeb[26]
-		gn io_oeb[27]
-		gn io_oeb[28]
-		gn io_oeb[29]
-		gn io_oeb[30]
-		gn io_oeb[31]
-		gn io_oeb[32]
-		gn io_oeb[33]
-		gn io_oeb[34]
-		gn io_oeb[35]
-		gn io_oeb[36]
-		gn io_oeb[37]
+		gn gpio_analog[0]
+		gn gpio_analog[1]
+		gn gpio_analog[2]
+		gn gpio_analog[3]
+		gn gpio_analog[4]
+		gn gpio_analog[5]
+		gn gpio_analog[6]
+		gn gpio_analog[7]
+		gn gpio_analog[8]
+		gn gpio_analog[9]
+		gn gpio_analog[10]
+		gn gpio_analog[11]
+		gn gpio_analog[12]
+		gn gpio_analog[13]
+		gn gpio_analog[14]
+		gn gpio_analog[15]
+		gn gpio_analog[16]
+		gn gpio_analog[17]
+		gn gpio_noesd[0]
+		gn gpio_noesd[1]
+		gn gpio_noesd[2]
+		gn gpio_noesd[3]
+		gn gpio_noesd[4]
+		gn gpio_noesd[5]
+		gn gpio_noesd[6]
+		gn gpio_noesd[7]
+		gn gpio_noesd[8]
+		gn gpio_noesd[9]
+		gn gpio_noesd[10]
+		gn gpio_noesd[11]
+		gn gpio_noesd[12]
+		gn gpio_noesd[13]
+		gn gpio_noesd[14]
+		gn gpio_noesd[15]
+		gn gpio_noesd[16]
+		gn gpio_noesd[17]
 		q
 	cvcin
-else
+elif [[ $DESIGN_NAME == *user_project_wrapper ]]; then
 	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
 		c 6
 		gn io_in[0]
@@ -298,10 +327,79 @@ else
 		gn io_oeb[35]
 		gn io_oeb[36]
 		gn io_oeb[37]
+		gn io_in[0]
+		gn io_in[1]
+		gn io_in[2]
+		gn io_in[3]
+		gn io_in[4]
+		gn io_in[5]
+		gn io_in[6]
+		gn io_in[7]
+		gn io_in[8]
+		gn io_in[9]
+		gn io_in[10]
+		gn io_in[11]
+		gn io_in[12]
+		gn io_in[13]
+		gn io_in[14]
+		gn io_in[15]
+		gn io_in[16]
+		gn io_in[17]
+		gn io_in[18]
+		gn io_in[19]
+		gn io_in[20]
+		gn io_in[21]
+		gn io_in[22]
+		gn io_in[23]
+		gn io_in[24]
+		gn io_in[25]
+		gn io_in[26]
+		gn io_in[27]
+		gn io_in[28]
+		gn io_in[29]
+		gn io_in[30]
+		gn io_in[31]
+		gn io_in[32]
+		gn io_in[33]
+		gn io_in[34]
+		gn io_in[35]
+		gn io_in[36]
+		gn io_in[37]
+		gn analog_io[0]
+		gn analog_io[1]
+		gn analog_io[2]
+		gn analog_io[3]
+		gn analog_io[4]
+		gn analog_io[5]
+		gn analog_io[6]
+		gn analog_io[7]
+		gn analog_io[8]
+		gn analog_io[9]
+		gn analog_io[10]
+		gn analog_io[11]
+		gn analog_io[12]
+		gn analog_io[13]
+		gn analog_io[14]
+		gn analog_io[15]
+		gn analog_io[16]
+		gn analog_io[17]
+		gn analog_io[18]
+		gn analog_io[19]
+		gn analog_io[20]
+		gn analog_io[21]
+		gn analog_io[22]
+		gn analog_io[23]
+		gn analog_io[24]
+		gn analog_io[25]
+		gn analog_io[26]
+		gn analog_io[27]
+		gn analog_io[28]
 		q
 	cvcin
+else
+	echo "ERROR: unrecognized top block $DESIGN_NAME"
+	exit 3
 fi
-
 
 start_time=$SECONDS
 cvc_rv -i $WORK_ROOT/cvcrc.oeb <$WORK_ROOT/cvc.oeb.script
@@ -315,7 +413,7 @@ seconds=$(((runtime % 3600) % 60))
 printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$WORK_ROOT/cvc.log
 
 if [[ $WORK_ROOT != $LOG_ROOT ]]; then
-	cp $WORK_ROOT/cvc.log $LOG_ROOT/cvc.oeb.log
+	cp $WORK_ROOT/cvc.oeb.log $LOG_ROOT/cvc.oeb.log
 fi
 
 awk '
@@ -323,7 +421,19 @@ awk '
 		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
 		getline;
 		getline;
-		in_connections[net] = $3 + $5 + $7;
+		in_connections[net] += $3 + $5 + $7;
+	}
+	/^> gn analog_io/ {
+		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
+		getline;
+		getline;
+		analog_connections[net+7] += $3 + $5 + $7;
+	}
+	/^> gn gpio_analog/ || /^> gn gpio_noesd/ {
+		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
+		getline;
+		getline;
+		analog_connections[net+7] += $3 + $5 + $7;
 	}
 	/^> gn io_out/ {
 		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
@@ -343,6 +453,11 @@ awk '
 					min[net] = $1;
 					getline;
 				}
+			} else if ( /^Sim path/ ) {
+				while ( NF > 0 ) {
+					sim[net] = $1;
+					getline;
+				}
 			} else if ( /^Max path/ ) {
 				while ( NF > 0 ) {
 					max[net] = $1;
@@ -357,30 +472,43 @@ awk '
 		}
 	}
 	END {
+		print "oeb connections:", length(oeb_connections);
 		for ( i in oeb_connections ) {
-			if ( in_connections[i] > 0 && out_connections[i] > 0 ) {
-				if ( min[i] !~ /vss/ || ! ( max[i] ~ /vdd/ || max[i] ~ /vcc/ ) ) {
-					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
+			if ( analog_connections[i] > 0 ) {
+				if ( in_connections[i] > 0 || out_connections[i] > 0 ) {
+					printf "ERROR: analog and digital connections at gpio-%d ", i;
+					printf "analog:%d in:%d out%d ", analog_connections[i], in_connections[i], out_connections[i];
+					printf "oeb: min/sim/max=%s/%s/%s\n", min[i], sim[i], max[i];
+				} else if ( ! ( sim[i] ~ /vdd/ ) ) {
+					printf "Warning: oeb should always be high for analog gpio-%d ", i;
+					printf "analog:%d oeb: min/sim/max=%s/%s/%s\n", analog_connections[i], min[i], sim[i], max[i];
 				}
-			} else if ( in_connections[i] > 0 ) {
-				if ( ! ( max[i] ~ /vdd/ || max[i] ~ /vcc/ ) ) {
-					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
+			} else if ( in_connections[i] > 0 && out_connections[i] == 0 ) {
+				if ( ! ( sim[i] ~ /vdd/ ) ) {
+					printf "Warning: oeb should always be high for input only gpio-%d ", i;
+					printf "in:%d out:%d oeb: min/sim/max=%s/%s/%s\n", in_connections[i], out_connections[i], min[i], sim[i], max[i];
 				}
 			} else if ( out_connections[i] > 0 ) {
 				if ( min[i] !~ /vss/ ) {
-					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
+					printf "ERROR: oeb must have possible low for output gpio-%d ", i;
+					printf "in:%d out:%d oeb: min/sim/max=%s/%s/%s\n", in_connections[i], out_connections[i], min[i], sim[i], max[i];
 				}
 			}
+			#print "gpio-" i, "analog:", analog_connections[i], "in:", in_connections[i], "out:", out_connections[i], "oeb: " min[i] "/" sim[i] "/" max[i];
 		}
 	}' $LOG_ROOT/cvc.oeb.log > $SIGNOFF_ROOT/cvc.oeb.report
 
 if [[ $cvc_status -eq 0 && $(grep '^CVC: End:' $LOG_ROOT/cvc.oeb.log | wc -l) -ne 1 ]]; then
 	# CVC finished abnormally
-	exit 3
-
-elif [[ $cvc_status -eq 0 && $(cat $SIGNOFF_ROOT/cvc.oeb.report | wc -w) -gt 0 ]]; then
-	# CVC finished normally, but detected errors
 	exit 4
+
+elif [[ $cvc_status -eq 0 && $(grep '^ERROR' $SIGNOFF_ROOT/cvc.oeb.report | wc -w) -gt 0 ]]; then
+	# CVC finished normally, but detected errors
+	exit 5
+
+elif [[ $cvc_status -eq 0 && $(grep '^Warning' $SIGNOFF_ROOT/cvc.oeb.report | wc -w) -gt 0 ]]; then
+	# CVC finished normally, but detected warings
+	exit 6
 
 else
 	exit $cvc_status
