Changes for integration to caravel CI
Added  LVS_ROOT, LOG_ROOT, SIGNOFF_ROOT, WORK_ROOT.
Converted bash ‘[‘ ‘]’ ->  ‘[[‘ ‘]]’
Changed awk printf to bash printf

diff --git a/run_cvc b/run_cvc
--- a/run_cvc
+++ b/run_cvc
@@ -1,19 +1,37 @@
 #! /bin/bash
 
+: "${LVS_ROOT:=$(pwd)}"
+: "${LOG_ROOT:=$(pwd)}"
+: "${SIGNOFF_ROOT:=$(pwd)}"
+: "${WORK_ROOT:=$(pwd)}"
+export LVS_ROOT LOG_ROOT SIGNOFF_ROOT WORK_ROOT
+
 export DESIGN_NAME=$1
-export RESULTS_DIR=$DESIGN_NAME.ext
+export RESULTS_DIR=$WORK_ROOT/$DESIGN_NAME.ext
 
 if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.cdl ]] ; then
-	echo "Creating $RESULTS_DIR/$DESIGN_NAME.cdl"
-	./spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice | \
-		gzip -c > $RESULTS_DIR/$DESIGN_NAME.cdl.gz
+	if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.gds.spice ]]; then
+		echo "Could not create cdl file from $RESULTS_DIR/$DESIGN_NAME.gds.spice"
+		exit 1
+	else
+		echo "Creating $RESULTS_DIR/$DESIGN_NAME.cdl"
+		$LVS_ROOT/spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice | \
+			gzip -c > $RESULTS_DIR/$DESIGN_NAME.cdl.gz
+	fi
+fi
+
+if [[ ( ! -f $WORK_ROOT/$DESIGN_NAME.power ) && -f $LVS_ROOT/cvc/$DESIGN_NAME.power ]]; then
+	cp $LVS_ROOT/cvc/$DESIGN_NAME.power $WORK_ROOT/$DESIGN_NAME.power
 fi
 
 start_time=$SECONDS
-cvc cvc/cvcrc.sky130B
+cvc_rv $LVS_ROOT/cvc/cvcrc.sky130B
 
 runtime=$(( SECONDS - start_time ))
 hours=$((runtime / 3600))
 minutes=$(( (runtime % 3600) / 60 ))
 seconds=$(( (runtime % 3600) % 60 ))
-awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $DESIGN_NAME.cvc.log
+printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $WORK_ROOT/$DESIGN_NAME.cvc.log
+
+cp $WORK_ROOT/$DESIGN_NAME.cvc.log $LOG_ROOT/.
+cp $WORK_ROOT/$DESIGN_NAME.cvc.log $SIGNOFF_ROOT/.
