More changes for 2409 including cheetah related
check_extraction: allow multiple diretories
check_extraction: show illegal overlaps from feedback
run_be_checks: check for environment variables
run_be_checks: WORK_ROOT must be empty or end in top cell name (prevents unintended overwrites)
Added missing lvs_config.json files to sky130A
set_lvs_env.py: Allow multiple includes of the same lvs_config.json file, but don't recurse in them. This allows, for example, multiple standard cell libraries.
run_gpio-id_check: Use TOP_LAYOUT as the default work directory
spice/sky130_ef_io__analog.spice: changed diode models to 'X'
tech/sky130?/cvc.models: added sky130_fd_pr__esd_pfet_g5v0d10v5
tech/sky130?/sky130?_setup.tcl: reduce 'ef_sc' and fd_sc' abstract cells the same
tech/sky130?/sky130?_setup.tcl: check for prefix and suffix at the same time when equating

diff --git a/run_be_checks b/run_be_checks
--- a/run_be_checks
+++ b/run_be_checks
@@ -48,9 +48,17 @@ if [[ $# -gt 4 ]]; then
 	exit 1
 fi
 
-# Check for LVS_ROOT
+# Check for LVS_ROOT, PDK_ROOT and PDK
 if [[ -z "$LVS_ROOT" ]]; then
 	echo "LVS_ROOT not set."
+	exit 1
+fi
+if [[ -z "$PDK_ROOT" ]]; then
+	echo "PDK_ROOT not set."
+	exit 1
+fi
+if [[ -z "$PDK" ]]; then
+	echo "PDK not set."
 	exit 1
 fi
 
@@ -93,6 +101,11 @@ fi
 export LOG_ROOT SIGNOFF_ROOT WORK_ROOT
 
 mkdir -p $LOG_ROOT $SIGNOFF_ROOT $WORK_ROOT
+if [[ ${WORK_ROOT##*/} != $TOP_SOURCE && $(find $WORK_ROOT | wc -l) -gt 1 ]]; then
+	echo ${WORK_ROOT##*/} $TOP_SOURCE $(find $WORK_ROOT | wc -l)
+	echo "Error: $WORK_ROOT must be empty or match $TOP_SOURCE"
+	exit 1
+fi
 rm -f $LOG_ROOT/{soft,lvs,cvc}.log $SIGNOFF_ROOT/{soft,lvs,cvc}.report $SIGNOFF_ROOT/hier.csv
 if [[ $SKIP_OEB == no ]]; then
 	rm -f $LOG_ROOT/cvc.oeb.log $SIGNOFF_ROOT/cvc.oeb.report
