Initial version of unified LVS configuration file

diff --git a/run_be_checks b/run_be_checks
--- a/run_be_checks
+++ b/run_be_checks
@@ -21,91 +21,76 @@
 #  3. Run full lvs
 #  4. Run cvc for digital designs
 #  
-#  Add cells to be flattened before extract to 'flatglob' file
-#  Add cells to be extracted as black-boxes to 'abstract' file
-#  Add cells to be flattened during compare to 'flatten' file
-#  Add cells not to be flattened during compare to 'noflatten' file
+#  All variable specified in LVS configuration file
 
-#  verilog_files defaults to the contents of ../verilog/gl
-#  spice_files contains common spice libraries, but may need to be changed.
+# Usage
+# run_be_checks LVS_config_file [top_netlist [top_layout]] 		: extract, then check
+# run_be_checks --noextract LVS_config_file [top_netlist [top_layout]]	: use previous extraction results to compare
 
-# Use cases
-# run_be_checks top_block netlist_file gds_file	: extract, then check
-# run_be_checks top_block netlist_file		: use previous extraction results to compare
-# run_be_checks 				: use previous extraction results to compare
-if [[ $# -eq 0 ]]; then
-	export LAYOUT=$(ls gds/user_*wrapper.gds* | head -1)
-	file=${LAYOUT##*/}
-	export TOP=${file%%.gds*}
-	if [[ "$TOP" == user_project_wrapper ]]; then
-		export NETLIST=verilog/gl/$TOP.v
-	else
-		export NETLIST=xschem/$TOP.spice
-	fi
-elif [[ $# -lt 2 || $# -gt 3 ]]; then
-	echo "usage: run_be_checks [top_block netlist_file [gds_file]]"
-	exit
+if [[ $1 = "--noextract" ]]; then
+	export EXTRACT_LAYOUT=no
+	shift
 else
-	export TOP=$1
-	export NETLIST=$2
-	if [[ $# -eq 3 ]]; then
-		export LAYOUT=$3
-	else
-		export LAYOUT=
-	fi
+	export EXTRACT_LAYOUT=yes
+fi
+	
+if [[ $# -lt 1 || $# -gt 3 ]]; then
+	echo "usage: run_be_checks [--noextract] lvs_config_file [netlist_top [layout_top]]"
+	exit 1
 fi
 
-echo "TOP: $TOP"
-echo "NETLIST: $NETLIST"
-echo "LAYOUT: $LAYOUT"
+CONFIG_FILE=$1
+TOP_SOURCE=$2
+TOP_LAYOUT=${3:-$TOP_SOURCE}
 
-: "${LOG_ROOT:=$(pwd)}"
+if [[ ! -f $CONFIG_FILE ]]; then
+	echo "Could not find LVS configuration file $CONFIG_FILE"
+	exit 1
+fi
+
+#get_lvs_config $CONFIG_FILE | 
+	source $CONFIG_FILE
+if [[ $EXTRACT_LAYOUT = no ]]; then
+	export LAYOUT_FILE=
+fi
+
+echo "TOP SOURCE: $TOP_SOURCE"
+echo "SOURCE FILE(S): $LVS_SPICE_FILES $LVS_VERILOG_FILES"
+echo "TOP LAYOUT: $TOP_LAYOUT"
+echo "LAYOUT FILE: $LAYOUT_FILE"
+
+: "${LOG_ROOT:=$(pwd)/$TOP_SOURCE}"
 : "${LVS_ROOT:=$(pwd)}"
-: "${SIGNOFF_ROOT:=$(pwd)}"
-: "${WORK_ROOT:=$(pwd)}"
+: "${SIGNOFF_ROOT:=$(pwd)/$TOP_SOURCE}"
+: "${WORK_ROOT:=$(pwd)/$TOP_SOURCE}"
 export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT
 
 if [[ ! -d $WORK_ROOT ]]; then
-	mkdir $WORK_ROOT
+	mkdir -p $WORK_ROOT/$TOP_SOURCE 
+	mkdir -p $WORK_ROOT/$TOP_LAYOUT
 fi
 
-if [[ ! -f $WORK_ROOT/$TOP.verilog_files ]]; then
-	if [[ -f $LVS_ROOT/$PDK/verilog_files ]]; then
-		cp $LVS_ROOT/$PDK/verilog_files $WORK_ROOT/$PDK/$TOP.verilog_files
-	elif [[ -d verilog/gl && $(ls verilog/gl | wc -l) -gt 0 ]]; then
-		ls verilog/gl/* > $WORK_ROOT/$TOP.verilog_files
-	elif [[ $PWD == $WORK_ROOT && -d ../verilog/gl && $(ls ../verilog/gl | wc -l) -gt 0 ]]; then
-		ls ../verilog/gl/* > $WORK_ROOT/$TOP.verilog_files
-	fi
-fi
-if [[ ! -f $WORK_ROOT/$TOP.spice_files ]]; then
-	echo "Warning: using $LVS_ROOT/$PDK/spice_files for $WORK_ROOT/$TOP.spice_files"
-	cp $LVS_ROOT/$PDK/spice_files $WORK_ROOT/$TOP.spice_files
-fi
+$LVS_ROOT/run_hier_check $TOP_SOURCE "$LVS_VERILOG_FILES" $TOP_LAYOUT $LAYOUT_FILE
 
-$LVS_ROOT/run_hier_check $TOP $NETLIST $LAYOUT
-zgrep STRNAME $WORK_ROOT/gds_text/$TOP.gds.txt.gz | \
-	awk '{print $2}' > $WORK_ROOT/gds_text/$TOP.cells
+$LVS_ROOT/run_scheck $CONFIG_FILE $TOP_LAYOUT $LAYOUT_FILE
 
-$LVS_ROOT/run_scheck $TOP $LAYOUT
+$LVS_ROOT/run_full_lvs --noextract $CONFIG_FILE $TOP_SOURCE $TOP_LAYOUT
 
-$LVS_ROOT/run_full_lvs $TOP $NETLIST $TOP
-
-if [[ $TOP = "user_project_wrapper" ]]; then
-	$LVS_ROOT/run_cvc $TOP
+if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
+	$LVS_ROOT/run_cvc $TOP_LAYOUT
 fi
 
 echo "
 Soft check result:"
-tail -n 20 $LOG_ROOT/$TOP.soft.log | awk '/Final result/,/Logging/' | grep -v ^Logging
+tail -n 20 $LOG_ROOT/$TOP_LAYOUT/soft.log | awk '/Final result/,/Logging/' | grep -v ^Logging
 
 echo "
 LVS result:"
-tail -n 20 $LOG_ROOT/$TOP.lvs.log | awk '/Final result/,/Logging/' | grep -v ^Logging
+tail -n 20 $LOG_ROOT/$TOP_SOURCE/lvs.log | awk '/Final result/,/^END/' | grep -v ^Logging | grep -v "^END"
 
-if [[ $TOP = "user_project_wrapper" ]]; then
+if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
 	echo "
 CVC result:"
-	grep 'CVC: Total:' $LOG_ROOT/$TOP.cvc.log
+	grep 'CVC: Total:' $LOG_ROOT/$TOP_LAYOUT/cvc.log
 fi
 	
diff --git a/run_hier_check b/run_hier_check
--- a/run_hier_check
+++ b/run_hier_check
@@ -20,24 +20,24 @@
 #  2. Extract gds/oas hierachy, if necessary.
 #  3. Compare
 #  
-#  Add verilog files to '$WORK_ROOT/verilog_files'
 
 # Use case
-# run_hier_check top_netlist_block netlist gds_file [primitive_prefix [gds_prefix]]
-if [ $# -lt 3 -o $# -gt 5 ]; then
-	echo "usage: run_hier_check top_netlist_block netlist gds_file [primitive_prefix [gds_prefix]]"
-	exit
+# run_hier_check top_source verilog_files top_layout layout_file [primitive_prefix [gds_prefix]]
+if [[ $# -lt 4 || $# -gt 6 ]]; then
+	echo "usage: run_hier_check top_source verilog_files top_layout gds_file [primitive_prefix [gds_prefix]]"
+	exit 1
 fi
 
-export TOP_NET=$1
-export NETLIST=$2
-export LAYOUT=$3
+export TOP_SOURCE=$1
+export SOURCE_FILES=$2
+export TOP_LAYOUT=$3
+export LAYOUT_FILE=$4
 PRIMITIVE_PREFIX_FILTER='-e s/\<sky130_([^/_]*_)*_//'
-if [ $# -ge 4 ]; then  # only if prefix is specified
+if [[ $# -ge 5 ]]; then  # only if prefix is specified
 	PRIMITIVE_PREFIX_FILTER="-e s/\\<$4//g"
 fi
 GDS_PREFIX_FILTER='-e s/^([A-Z0-9][A-Z0-9]_)*// -e s/\/([A-Z0-9][A-Z0-9]_)*/\//'
-if [ $# -eq 5 ]; then  # only if prefix is specified
+if [[ $# -eq 6 ]]; then  # only if prefix is specified
 	GDS_PREFIX_FILTER="-e s/^($5)*// -e s/\/($5)*/\//"
 fi
 
@@ -47,149 +47,172 @@ fi
 : "${WORK_ROOT:=$(pwd)}"
 export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT
 
-log_file=$LOG_ROOT/$TOP_NET.hier.log
-verilog_cell_file=$WORK_ROOT/$TOP_NET.verilog.cells
+mkdir -p $LOG_ROOT/$TOP_SOURCE
+mkdir -p $SIGNOFF_ROOT/$TOP_SOURCE
+mkdir -p $WORK_ROOT/$TOP_SOURCE
+mkdir -p $WORK_ROOT/$TOP_LAYOUT
+
+log_file=$LOG_ROOT/$TOP_SOURCE/hier.log
+verilog_cell_file=$WORK_ROOT/$TOP_SOURCE/verilog.cells
+layout_cell_file=$WORK_ROOT/$TOP_LAYOUT/layout.cells
+
+echo " "
+echo "Running hierarchical comparison between verilog and layout..."
 
 date "+BEGIN: %c" > $log_file
 start_time=$SECONDS
 
-
-echo "Creating $verilog_cell_file from the following files..." | \
-	tee -a $log_file
-echo "	" $NETLIST | \
-	tee -a $log_file
-if [[ -f $WORK_ROOT/$TOP_NET.verilog_files ]]; then
-	grep -v ^# $WORK_ROOT/$TOP_NET.verilog_files | \
-		sed -e 's,$::env(\([^)]*\)),$\1,' | \
-		envsubst > $WORK_ROOT/$TOP_NET.verilog_files.bash
-	awk '{print "	" $1}' $WORK_ROOT/$TOP_NET.verilog_files.bash | \
+if [[ $(echo $SOURCE_FILES | wc -w) -gt 0 ]]; then
+	echo "Creating $verilog_cell_file from the following files..." | \
 		tee -a $log_file
+	echo $SOURCE_FILES | \
+		sed -e 's/  */\n/g' | \
+		sed -e 's/^/	/' | \
+		tee -a $log_file
+
+	sed '/^[ 	]*module[ 	].*[^ 	](/s/(/ (/' `echo $SOURCE_FILES` | \
+		awk -v top=$TOP_SOURCE '
+			$1 ~ /^\/\*/ {
+				while ( ! /\*\// ) {
+					getline;
+				}
+			}
+			$1 == "module" {
+				if ( $2 in modules ) {
+					print "Duplicate module definition", $2 > "'$log_file'";
+				}
+				if ( ! ( $2 in cells ) ) {
+					cells[$2] = 1;
+				}
+				module = $2;
+				next;
+			}
+			$1 ~ /^\/\// {
+				next;
+			}
+			/ \(/ && ! /^[ 		]*\/\*/ {
+				key = module "/" $1;
+				if ( ! ( $1 in cells ) ) {
+					cells[$1] = 1;
+				}
+				if ( key in hier ) {
+					hier[key] += 1;
+				} else {
+					subcells[module] = subcells[module] " " $1;
+					hier[key] = 1;
+				}
+			}
+			END {
+				print_subckt[top] = 1;
+				AddPrintSubckts(subcells[top]);
+				for ( key in hier ) {
+					split(key, path, "/");
+					if ( path[1] in print_subckt ) {
+						print key, hier[key];
+					}
+				}
+				for ( cell in cells ) {
+					print cell > "'$verilog_cell_file'";
+				}
+			}
+			function AddPrintSubckts(subckt_list, subckts, subckt_it) {
+				subcell_count = split(subckt_list, subckts);
+				for ( subckt_it in subckts ) {
+					print_subckt[subckts[subckt_it]] = 1;
+					AddPrintSubckts(subcells[subckts[subckt_it]]);
+				}
+			}' - | \
+		grep -v // | \
+		sed -E $PRIMITIVE_PREFIX_FILTER | \
+		sort > $WORK_ROOT/$TOP_SOURCE/verilog.hier
 else
-	rm -f $WORK_ROOT/$TOP_NET.verilog_files.bash
-	touch $WORK_ROOT/$TOP_NET.verilog_files.bash
+	echo "No verilog files..."
+	rm -f $WORK_ROOT/$TOP_SOURCE/verilog.hier $verilog_cell_file
+	touch $WORK_ROOT/$TOP_SOURCE/verilog.hier 
+	cat > $verilog_cell_file <<-EOF
+		$TOP_SOURCE
+	EOF
 fi
 
-sed '/^[ 	]*module[ 	].*[^ 	](/s/(/ (/' $NETLIST `cat $WORK_ROOT/$TOP_NET.verilog_files.bash | grep -v ^#` | \
-	awk -v top=$TOP_NET '
-		$1 ~ /^\/\*/ {
-			while ( ! /\*\// ) {
-				getline;
-			}
-		}
-		$1 == "module" {
-			if ( $2 in modules ) {
-				print "Duplicate module definition", $2 > "'$log_file'";
-			}
-			if ( ! ( $2 in cells ) ) {
-				cells[$2] = 1;
-			}
+if [[ $LAYOUT_FILE ]]; then
+	if [[ ${LAYOUT_FILE##*.} == "gz" ]]; then
+		CAT=zcat
+		BASE_LAYOUT=${LAYOUT_FILE%.gz}
+	else
+		CAT=cat
+		BASE_LAYOUT=$LAYOUT_FILE
+	fi
+	EXT=${BASE_LAYOUT##*.}
+	if [[ "$EXT" == "txt" ]]; then
+		TEXT_FILE=$BASE_LAYOUT	
+	elif [[ "$EXT" == "gds" || "$EXT" == "oas" ]]; then
+		TEXT_FILE=$WORK_ROOT/$TOP_LAYOUT/layout.txt
+		cat > $WORK_ROOT/$TOP_LAYOUT/gds2txt.py <<-EOF
+			import pya
+			
+			app = pya.Application.instance()
+			opt = pya.SaveLayoutOptions()
+			layout_view = pya.Layout()
+			
+			input_layout = "$LAYOUT_FILE"
+			output = "$TEXT_FILE"
+			# Setting the name of the output file and setting the substitution character
+			print("[INFO] Changing from " + input_layout + "\n	to " + output)
+			opt.set_format_from_filename(output)
+			opt.oasis_substitution_char=''
+			
+			# Reading the input file and writing it to the output file name
+			layout_view.read(input_layout)
+			for cell_it in layout_view.each_cell():
+			    if cell_it.name.endswith("$TOP_LAYOUT"):
+			       myIndex = layout_view.cell(cell_it.name).cell_index()
+			       break
+			opt.select_cell(myIndex)
+			opt.add_layer(0, pya.LayerInfo())
+			layout_view.write(output, opt)
+		
+			app.exit(0)
+		EOF
+		klayout -b -rm $WORK_ROOT/$TOP_LAYOUT/gds2txt.py | \
+			tee -a $log_file
+		gzip -f $TEXT_FILE
+		CAT=zcat
+	fi
+
+	$CAT $TEXT_FILE | \
+	awk '
+		/^STRNAME/ {
 			module = $2;
-			next;
 		}
-		$1 ~ /^\/\// {
-			next;
-		}
-		/ \(/ && ! /^[ 		]*\/\*/ {
-			key = module "/" $1;
-			if ( ! ( $1 in cells ) ) {
-				cells[$1] = 1;
-			}
+		/^SNAME/ {
+			key = module "/" $2;
 			if ( key in hier ) {
 				hier[key] += 1;
 			} else {
-				subcells[module] = subcells[module] " " $1;
 				hier[key] = 1;
 			}
 		}
 		END {
-			print_subckt[top] = 1;
-			AddPrintSubckts(subcells[top]);
 			for ( key in hier ) {
-				split(key, path, "/");
-				if ( path[1] in print_subckt ) {
-					print key, hier[key];
-				}
-			}
-			for ( cell in cells ) {
-				print cell > "'$verilog_cell_file'";
-			}
-		}
-		function AddPrintSubckts(subckt_list, subckts, subckt_it) {
-			subcell_count = split(subckt_list, subckts);
-			for ( subckt_it in subckts ) {
-				print_subckt[subckts[subckt_it]] = 1;
-				AddPrintSubckts(subcells[subckts[subckt_it]]);
+				print key, hier[key];
 			}
 		}' - | \
-	grep -v // | \
-	sed -E $PRIMITIVE_PREFIX_FILTER | \
-	sort > $WORK_ROOT/$TOP_NET.verilog.hier
-
-if [ ${LAYOUT##*.} == "gz" ]; then
-	CAT=zcat
-	BASE_LAYOUT=${LAYOUT%.gz}
+		sed -E $GDS_PREFIX_FILTER $PRIMITIVE_PREFIX_FILTER | \
+		sort -u > $WORK_ROOT/$TOP_LAYOUT/layout.hier
+	$CAT $TEXT_FILE | \
+		grep STRNAME | \
+		awk '{print $2}' > $WORK_ROOT/$TOP_LAYOUT/layout.cells
+		
+elif [[ -f $WORK_ROOT/$TOP_LAYOUT/layout.hier ]]; then
+	echo "Reusing $WORK_ROOT/$TOP_LAYOUT/layout.hier"
 else
-	CAT=cat
-	BASE_LAYOUT=$LAYOUT
-fi
-EXT=${BASE_LAYOUT##*.}
-if [ "$EXT" == "txt" ]; then
-	TEXT_FILE=$BASE_LAYOUT	
-elif [ "$EXT" == "gds" -o "$EXT" == "oas" ]; then
-	TEXT_FILE=$WORK_ROOT/gds_text/$TOP_NET.gds.txt
-	mkdir -p $WORK_ROOT/gds_text
-	echo "Creating $TEXT_FILE.gz from $LAYOUT..." | \
-		tee -a $log_file
-cat > $WORK_ROOT/gds2txt.py <<-EOF
-	import pya
-	
-	app = pya.Application.instance()
-	opt = pya.SaveLayoutOptions()
-	view = pya.Layout()
-	
-	input_layout = "$LAYOUT"
-	output = "$TEXT_FILE"
-	# Setting the name of the output file and setting the substitution character
-	print("[INFO] Changing from " + input_layout + " to " + output)
-	opt.set_format_from_filename(output)
-	opt.oasis_substitution_char=''
-	
-	# Reading the input file and writing it to the output file name
-	view.read(input_layout)
-	view.write(output, opt)
-	
-	app.exit(0)
-EOF
-	klayout -b -rm $WORK_ROOT/gds2txt.py | \
-		tee -a $log_file
-	gzip -f $TEXT_FILE
-	CAT=zcat
+	echo "Could not locate $WORK_ROOT/$TOP_LAYOUT/layout.hier"
+	exit 1
 fi
 
-$CAT $TEXT_FILE | \
-awk '
-	/^STRNAME/ {
-		module = $2;
-	}
-	/^SNAME/ {
-		key = module "/" $2;
-		if ( key in hier ) {
-			hier[key] += 1;
-		} else {
-			hier[key] = 1;
-		}
-	}
-	END {
-		for ( key in hier ) {
-			print key, hier[key];
-		}
-	}' - | \
-	sed -E $GDS_PREFIX_FILTER $PRIMITIVE_PREFIX_FILTER | \
-	sort -u > $WORK_ROOT/$TOP_NET.layout.hier
-
-comm -23 $WORK_ROOT/$TOP_NET.verilog.hier $WORK_ROOT/$TOP_NET.layout.hier | \
+comm -23 $WORK_ROOT/$TOP_SOURCE/verilog.hier $WORK_ROOT/$TOP_LAYOUT/layout.hier | \
 	awk '{print $1}' | \
-	fgrep -f - $WORK_ROOT/$TOP_NET.verilog.hier $WORK_ROOT/$TOP_NET.layout.hier | \
+	fgrep -f - $WORK_ROOT/$TOP_SOURCE/verilog.hier $WORK_ROOT/$TOP_LAYOUT/layout.hier | \
 	sed 's/:/ /' | \
 	awk '	BEGIN {
 			print "verilog,,layout";
@@ -221,13 +244,13 @@ comm -23 $WORK_ROOT/$TOP_NET.verilog.hier $WORK_ROOT/$TOP_NET.layout.hier | \
 				match_count += 1;
 				print verilog[match_count] "," instances[verilog[match_count]];
 			}
-		}' - > $SIGNOFF_ROOT/$TOP_NET.hier.csv
+		}' - > $SIGNOFF_ROOT/$TOP_SOURCE/hier.csv
 
-if [[ $(cat $SIGNOFF_ROOT/$TOP_NET.hier.csv | wc -l) -eq 1 ]]; then
-	echo "Hierarchy check for $TOP_NET passed." | \
+if [[ $(cat $SIGNOFF_ROOT/$TOP_SOURCE/hier.csv | wc -l) -eq 1 ]]; then
+	echo "Hierarchy check for $TOP_SOURCE passed." | \
 		tee -a $log_file
 else
-	echo "Hierarchy check for $TOP_NET failed. See $SIGNOFF_ROOT/$TOP_NET.hier.csv" | \
+	echo "Hierarchy check for $TOP_SOURCE failed. See $SIGNOFF_ROOT/$TOP_SOURCE/hier.csv" | \
 		tee -a $log_file
 fi
 
diff --git a/run_scheck b/run_scheck
--- a/run_scheck
+++ b/run_scheck
@@ -1,5 +1,5 @@
 #! /bin/bash
-#   run_scheck: Detect well only connections in GDS file. Also run CVC for user_*project_wrapper.
+#   run_scheck: Detect well only connections in GDS file.
 
 #   Copyright 2022 D. Mitch Bailey  cvc at shuharisystem dot com
 
@@ -22,18 +22,25 @@
 #  4. Remove disconnected nets.
 #  5. Compare
 #  
-#  Add cells to be flattened before extract to 'flatglob' file
-#  Add cells to be extracted as black-boxes to 'abstract' file
-#  Add cells to be flattened during compare to 'flatten' file
-#  Add cells not to be flattened during compare to 'noflatten' file
+
 
 # Use cases
-# run_scheck top_block gds_file	: extract and then compare
-# run_scheck top_block		: use previous extraction results to compare
-if [ $# -lt 1 -o $# -gt 2 ]; then
-	echo "usage: run_scheck top_block [gds_file]"
-	exit
+# run_scheck [--noextract] lvs_config_file [top_block [gds_file]]	
+
+if [[ $1 = "--noextract" ]]; then
+	export EXTRACT_LAYOUT=no
+	shift
+else
+	export EXTRACT_LAYOUT=yes
 fi
+
+if [[ $# -lt 1 || $# -gt 3 ]]; then
+	echo "usage: run_scheck [--noextract] lvs_config_file [top_block [gds_file]]"
+	exit 1
+fi
+
+echo " "
+echo "Running soft connection check on layout..."
 
 # Check for PDK_ROOT and PDK
 if [[ -z "$PDK_ROOT" || -z "$PDK" ]]; then
@@ -56,116 +63,139 @@ fi
 : "${WORK_ROOT:=$(pwd)}"
 export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT
 
-export TOP=$1
-if [ ${TOP/*analog*/analog} == analog ]; then
+CONFIG_FILE=$1
+if [[ $# -ge 2 ]]; then
+	TOP_LAYOUT=$2
+fi
+if [[ $# -ge 3 ]]; then
+	LAYOUT_FILE=$3
+fi
+
+if [[ ! -f $CONFIG_FILE ]]; then
+	echo "Could not find LVS configuration file $CONFIG_FILE"
+	exit 1
+fi
+
+source $CONFIG_FILE
+export TOP=$TOP_LAYOUT
+if [[ $EXTRACT_LAYOUT = no ]]; then
+	export LAYOUT_FILE=
+fi
+
+echo "TOP: $TOP"
+echo "LAYOUT: $LAYOUT_FILE"
+
+mkdir -p $LOG_ROOT/$TOP
+mkdir -p $WORK_ROOT/$TOP
+mkdir -p $SIGNOFF_ROOT/$TOP
+
+if [[ ${TOP/*analog*/analog} = analog ]]; then
 	export EXT_TYPE=analog
 else
 	export EXT_TYPE=digital
 fi
 
-if [[ ! -f $WORK_ROOT/$TOP.flatglob && $LVS_ROOT/$PDK/flatglob ]]; then
-	echo "Warning: using $LVS_ROOT/$PDK/flatglob for $WORK_ROOT/$TOP.flatglob"
-	cp $LVS_ROOT/$PDK/flatglob $WORK_ROOT/$TOP.flatglob
-fi
-if [[ ! -f $WORK_ROOT/$TOP.abstract && -f $LVS_ROOT/$PDK/abstract ]]; then
-	echo "Warning: using $LVS_ROOT/$PDK/abstract for $WORK_ROOT/$TOP.abstract"
-	cp $LVS_ROOT/$PDK/abstract $WORK_ROOT/$TOP.abstract
-fi
-if [[ -f $WORK_ROOT/$TOP.abstract && -f $WORK_ROOT/gds_text/$TOP.cells ]]; then
-	sed -e 's/\*/.*/g' -e 's/^/^/' -e 's/$/$/' $WORK_ROOT/$TOP.abstract | \
-		grep -f - $WORK_ROOT/gds_text/$TOP.cells > $WORK_ROOT/$TOP.abstract.glob
+echo $EXTRACT_FLATGLOB | \
+	sed 's/  */\n/g' > $WORK_ROOT/$TOP/flatglob
+echo $EXTRACT_ABSTRACT | \
+	sed 's/  */\n/g' > $WORK_ROOT/$TOP/abstract
+if [[ -f $WORK_ROOT/$TOP/layout.cells ]]; then
+	sed -e 's/\*/.*/g' -e 's/^/^/' -e 's/$/$/' $WORK_ROOT/$TOP/abstract | \
+		grep -f - $WORK_ROOT/$TOP/layout.cells > $WORK_ROOT/$TOP/abstract.glob
+else
+	cp $WORK_ROOT/$TOP/abstract $WORK_ROOT/$TOP/abstract.glob
 fi
 
 # Add any cells that should be flattened before extraction to 'flatten'. globbing allowed.
-export FLATGLOB_CELLS="`cat $WORK_ROOT/$TOP.flatglob 2>/dev/null | grep -v '^#'`"
+export FLATGLOB_CELLS="`cat $WORK_ROOT/$TOP/flatglob 2>/dev/null | grep -v '^#'`"
 # Add any empty cells that should be extracted as black-boxes to 'abstract'.
-export ABSTRACT_CELLS="`cat $WORK_ROOT/$TOP.abstract.glob 2>/dev/null | grep -v '^#'`"
+export ABSTRACT_CELLS="`cat $WORK_ROOT/$TOP/abstract.glob 2>/dev/null | grep -v '^#'`"
 
 # Verify that magic and netgen are executable.
-which magic >& /dev/null
-if [[ $? != 0 ]]; then
+if ! which magic >& /dev/null; then
 	echo "Error: Could not execute magic."
 	exit 1
 fi
-which netgen >& /dev/null
-if [[ $? != 0 ]]; then
+if ! which netgen >& /dev/null; then
 	echo "Error: Could not execute netgen."
 	exit 1
 fi
 
 #  Create extraction result directories. No error if they already exist.
-mkdir -p $WORK_ROOT/$TOP.ext $WORK_ROOT/$TOP.nowell.ext
+echo "$WORK_ROOT/$TOP/ext"
+mkdir -p $WORK_ROOT/$TOP/ext
+mkdir -p $WORK_ROOT/$TOP/nowell.ext
 
-if [ $# == 1 ]; then
-	# No gds_file so LVS only. Check for existing extraction results.
-	if [ ! -f $WORK_ROOT/$TOP.ext/$TOP.gds.nowell.spice ]; then
-		echo "Error: missing $WORK_ROOT/$TOP.ext/$TOP.gds.nowell.spice"
-		echo "Specify gds_file to create"
-		echo "usage: run_scheck top_block [gds_file]"
-		exit
-	fi
-	if [ ! -f $WORK_ROOT/$TOP.nowell.ext/$TOP.gds.nowell.spice ]; then
-		echo "Error: missing $WORK_ROOT/$TOP.nowell.ext/$TOP.gds.nowell.spice"
-		echo "Specify gds_file to create"
-		echo "usage: run_scheck top_block [gds_file]"
-		exit
-	fi
-else
+if [[ $LAYOUT_FILE ]]; then
 	# Specified gds_file, so extract it.
-	export CURRENT_GDS=$2
 
-	if [ ! -f $CURRENT_GDS ]; then
-		echo "Error: File not found: $CURRENT_GDS"
+	if [[ ! -f $LAYOUT_FILE ]]; then
+		echo "Error: File not found: $LAYOUT_FILE"
 		exit 2
 	fi
 
 	# Remove any previous extraction results
-	rm -rf $WORK_ROOT/{$TOP.ext,$TOP.nowell.ext}/*.ext{,.gz}
+	find $WORK_ROOT/$TOP/{ext,nowell.ext} -type f -name '*.ext' -delete
+	find $WORK_ROOT/$TOP/{ext,nowell.ext} -type f -name '*.ext.gz' -delete
 
-	export RUN_DIR=$WORK_ROOT/$TOP.ext
-	echo "Extracting layout with well in background process. See $LOG_ROOT/$TOP.ext.log."
+	export RUN_DIR=$WORK_ROOT/$TOP/ext
+	echo "Extracting layout with well in background process. See $LOG_ROOT/$TOP/ext.log."
 	#  1. Extract gds_file with well connectivity
-	( date "+BEGIN: %c" > $LOG_ROOT/$TOP.ext.log; \
+	( date "+BEGIN: %c" > $LOG_ROOT/$TOP/ext.log; \
 	start_time=$SECONDS; \
-	magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.well $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl < /dev/null >> $LOG_ROOT/$TOP.ext.log 2>&1; \
+	magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.well $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl < /dev/null >> $LOG_ROOT/$TOP/ext.log 2>&1; \
 	#  2. Remove well connections and disconnected nets.; \
 	sed -f $LVS_ROOT/scripts/remove_well.sed $RUN_DIR/$TOP.gds.spice | \
 		awk -f $LVS_ROOT/scripts/remove_disconnect.awk - > $RUN_DIR/$TOP.gds.nowell.spice; \
-	date "+END: %c" >> $LOG_ROOT/$TOP.ext.log; \
+	date "+END: %c" >> $LOG_ROOT/$TOP/ext.log; \
 	runtime=$(( SECONDS - start_time )); \
 	hours=$((runtime / 3600)); \
 	minutes=$(( (runtime % 3600) / 60 )); \
 	seconds=$(( (runtime % 3600) % 60 )); \
-	printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP.ext.log ) &
+	printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP/ext.log ) &
 
-	export RUN_DIR=$WORK_ROOT/$TOP.nowell.ext
-	echo "Extracting layout without well in background process. See $LOG_ROOT/$TOP.nowell.ext.log."
+	export RUN_DIR=$WORK_ROOT/$TOP/nowell.ext
+	echo "Extracting layout without well in background process. See $LOG_ROOT/$TOP/nowell.ext.log."
 	#  3. Extract gds_file without well connectivity
-	( date "+BEGIN: %c" > $LOG_ROOT/$TOP.nowell.ext.log; \
+	( date "+BEGIN: %c" > $LOG_ROOT/$TOP/nowell.ext.log; \
 	start_time=$SECONDS; \
-	magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.nowell $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl < /dev/null >> $LOG_ROOT/$TOP.nowell.ext.log 2>&1; \
+	magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.nowell $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl < /dev/null >> $LOG_ROOT/$TOP/nowell.ext.log 2>&1; \
 	#  4. Remove disconnected nets.; \
 	awk -f $LVS_ROOT/scripts/remove_disconnect.awk $RUN_DIR/$TOP.gds.spice > $RUN_DIR/$TOP.gds.nowell.spice; \
-	date "+END: %c" >> $LOG_ROOT/$TOP.nowell.ext.log; \
+	date "+END: %c" >> $LOG_ROOT/$TOP/nowell.ext.log; \
 	runtime=$(( SECONDS - start_time )); \
 	hours=$((runtime / 3600)); \
 	minutes=$(( (runtime % 3600) / 60 )); \
 	seconds=$(( (runtime % 3600) % 60 )); \
-	printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP.nowell.ext.log ) &
+	printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP/nowell.ext.log ) &
 
 	wait
 
 	# Compress large ext files
-	find $WORK_ROOT/$TOP.*ext -name '*.ext' -size +1M -exec gzip {} \;
+	find $WORK_ROOT/$TOP/*ext -name '*.ext' -size +1M -exec gzip {} \;
+else
+	# No gds_file so LVS only. Check for existing extraction results.
+	if [[ ! -f $WORK_ROOT/$TOP/ext/$TOP.gds.nowell.spice ]]; then
+		echo "Error: missing $WORK_ROOT/$TOP/ext/$TOP.gds.nowell.spice"
+		echo "Specify gds_file to create"
+		echo "usage: run_scheck top_block [gds_file]"
+		exit 2
+	fi
+	if [[ ! -f $WORK_ROOT/$TOP/nowell.ext/$TOP.gds.nowell.spice ]]; then
+		echo "Error: missing $WORK_ROOT/$TOP/nowell.ext/$TOP.gds.nowell.spice"
+		echo "Specify gds_file to create"
+		echo "usage: run_scheck top_block [gds_file]"
+		exit 2
+	fi
 fi
 
 #  5. Compare
-date "+BEGIN: %c" > $LOG_ROOT/$TOP.soft.log
+date "+BEGIN: %c" > $LOG_ROOT/$TOP/soft.log
 start_time=$SECONDS
-netgen -batch source $LVS_ROOT/tech/setup_file.soft.lvs | tee -a $LOG_ROOT/$TOP.soft.log 2>&1
-date "+END: %c" >> $LOG_ROOT/$TOP.soft.log
+netgen -batch source $LVS_ROOT/tech/setup_file.soft.lvs | tee -a $LOG_ROOT/$TOP/soft.log 2>&1
+date "+END: %c" >> $LOG_ROOT/$TOP/soft.log
 runtime=$(( SECONDS - start_time ))
 hours=$((runtime / 3600))
 minutes=$(( (runtime % 3600) / 60 ))
 seconds=$(( (runtime % 3600) % 60 ))
-printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP.soft.log
+printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $LOG_ROOT/$TOP/soft.log
