Changes for mpw_precheck integration
Require LVS_ROOT environment variable
Modified WORK_ROOT/LOG_ROOT/SIGNOFF_ROOT handling
Improved return code handling (non zero if error)
Use no labelcheck extraction parameter

diff --git a/run_be_checks b/run_be_checks
--- a/run_be_checks
+++ b/run_be_checks
@@ -39,6 +39,12 @@ if [[ $# -lt 1 || $# -gt 3 ]]; then
 	exit 1
 fi
 
+# Check for LVS_ROOT
+if [[ -z "$LVS_ROOT" ]]; then
+	echo "LVS_ROOT not set."
+	exit 1
+fi
+
 CONFIG_FILE=$1
 TOP_SOURCE=$2
 TOP_LAYOUT=${3:-$TOP_SOURCE}
@@ -60,37 +66,57 @@ echo "TOP LAYOUT: $TOP_LAYOUT"
 echo "LAYOUT FILE: $LAYOUT_FILE"
 
 : "${LOG_ROOT:=$(pwd)/$TOP_SOURCE}"
-: "${LVS_ROOT:=$(pwd)}"
 : "${SIGNOFF_ROOT:=$(pwd)/$TOP_SOURCE}"
 : "${WORK_ROOT:=$(pwd)/$TOP_SOURCE}"
-export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT
+export LOG_ROOT SIGNOFF_ROOT WORK_ROOT
 
-if [[ ! -d $WORK_ROOT ]]; then
-	mkdir -p $WORK_ROOT/$TOP_SOURCE 
-	mkdir -p $WORK_ROOT/$TOP_LAYOUT
-fi
+mkdir -p $LOG_ROOT $SIGNOFF_ROOT $WORK_ROOT
+
+start_time=$SECONDS
 
 $LVS_ROOT/run_hier_check $TOP_SOURCE "$LVS_VERILOG_FILES" $TOP_LAYOUT $LAYOUT_FILE
+hier_status=$?
 
 $LVS_ROOT/run_scheck $CONFIG_FILE $TOP_LAYOUT $LAYOUT_FILE
+scheck_status=$?
 
 $LVS_ROOT/run_full_lvs --noextract $CONFIG_FILE $TOP_SOURCE $TOP_LAYOUT
+lvs_status=$?
 
 if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
 	$LVS_ROOT/run_cvc $TOP_LAYOUT
+	cvc_status=$?
 fi
 
 echo "
 Soft check result:"
-tail -n 20 $LOG_ROOT/$TOP_LAYOUT/soft.log | awk '/Final result/,/Logging/' | grep -v ^Logging
+tail -n 20 $LOG_ROOT/soft.log | awk '/Final result/,/Logging/' | grep -v ^Logging
 
 echo "
 LVS result:"
-tail -n 20 $LOG_ROOT/$TOP_SOURCE/lvs.log | awk '/Final result/,/^END/' | grep -v ^Logging | grep -v "^END"
+tail -n 20 $LOG_ROOT/lvs.log | awk '/Final result/,/^END/' | grep -v ^Logging | grep -v "^END"
 
 if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
 	echo "
 CVC result:"
-	grep 'CVC: Total:' $LOG_ROOT/$TOP_LAYOUT/cvc.log
+	grep 'CVC: Total:' $LOG_ROOT/cvc.log
 fi
 	
+runtime=$(( SECONDS - start_time ))
+hours=$((runtime / 3600))
+minutes=$(( (runtime % 3600) / 60 ))
+seconds=$(( (runtime % 3600) % 60 ))
+printf "\nRuntime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds
+
+# If any of the checks had an error, set return code.
+# NOTE: ignores hierarchy check errors
+# NOTE: cvc_status ignored if not run
+if [[ $scheck_status -eq 0 && $lvs_status -eq 0 && ${cvc_status:=0} -eq 0 ]]; then
+	echo "
+No errors detected"
+	exit 0
+else
+	echo "
+WARNING: possible errors"
+	exit 1
+fi
